POST http://localhost:4000/api/signin
Content-Type: application/json

   {
    "title": "sample",
    "description": "sample 1",
    "venue": "kamakwa",
    "datetime": "Wed, 21 Oct 2015 18:27:50 GMT"
    }


